version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433" 
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - db
    